kind: pipeline
name: default
type: docker
steps: 
- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 18.218.155.101
    username: ubuntu
    key:
      from_secret: ssh_key
    port: 22
    script:
      - echo hello world
