kind: pipeline
name: default
type: docker
steps: 
- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 54.87.48.82
    username: ubuntu
    key:
      from_secret: ssh_key
    port: 22
    script:
      - echo hello
      - echo world
